name = "KloonMute Felis"
modid = "kloonmute"
description = """
KloonMute but its for Felis
"""
version = "${version}"

[[entrypoints]]
id = "common"
path = "dev.cosrnic.kloonmute.Mod"

[[entrypoints]]
id = "client"
path = "dev.cosrnic.kloonmute.client.Client"

[[mixins]]
path = "kloonmute.mixins.json"

[[transforms]]
name = "option transform"
target = "net.minecraft.client.Options"
path = "dev.cosrnic.kloonmute.OptionsTransformation"