name = "Example Mod"
modid = "example"
description = """
Cool description for your project.
"""
version = "${version}"

[[entrypoints]]
id = "common"
path = "org.example.mod.ExampleMod"

[[entrypoints]]
id = "client"
path = "org.example.mod.client.ExampleModClient"

[[mixins]]
path = "example.mixins.json"